//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testGestionDesNotes
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscrit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inscrit()
        {
            this.examen = new HashSet<examen>();
        }
    
        public int idEtudiant { get; set; }
        public int idGroupe { get; set; }
        public System.DateTime dateInscription { get; set; }
        public int idInscrit { get; set; }
    
        public virtual etudiant etudiant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examen> examen { get; set; }
        public virtual groupe groupe { get; set; }
    }
}
